# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: url_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='url_info.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0eurl_info.proto\"e\n\x0eUrlInfoMessage\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\r\n\x05other\x18\x03 \x01(\t\x12\x11\n\tproxy_url\x18\x04 \x01(\t\x12\x16\n\x0eheader_request\x18\x05 \x01(\tb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_URLINFOMESSAGE = _descriptor.Descriptor(
  name='UrlInfoMessage',
  full_name='UrlInfoMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='url', full_name='UrlInfoMessage.url', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='uuid', full_name='UrlInfoMessage.uuid', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='other', full_name='UrlInfoMessage.other', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='proxy_url', full_name='UrlInfoMessage.proxy_url', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='header_request', full_name='UrlInfoMessage.header_request', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['UrlInfoMessage'] = _URLINFOMESSAGE

UrlInfoMessage = _reflection.GeneratedProtocolMessageType('UrlInfoMessage', (_message.Message,), dict(
  DESCRIPTOR = _URLINFOMESSAGE,
  __module__ = 'url_info_pb2'
  # @@protoc_insertion_point(class_scope:UrlInfoMessage)
  ))
_sym_db.RegisterMessage(UrlInfoMessage)


# @@protoc_insertion_point(module_scope)
